.TH  "cwalld_selinux"  "8"  "26-03-15" "cwalld" "SELinux Policy cwalld"
.SH "NAME"
cwalld_selinux \- Security Enhanced Linux Policy for the cwalld processes
.SH "DESCRIPTION"

Security-Enhanced Linux secures the cwalld processes via flexible mandatory access control.

The cwalld processes execute with the cwalld_t SELinux type. You can check if you have these processes running by executing the \fBps\fP command with the \fB\-Z\fP qualifier.

For example:

.B ps -eZ | grep cwalld_t


.SH "ENTRYPOINTS"

The cwalld_t SELinux type can be entered via the \fBcwalld_exec_t\fP file type.

The default entrypoint paths for the cwalld_t domain are the following:


.SH PROCESS TYPES
SELinux defines process types (domains) for each process running on the system
.PP
You can see the context of a process using the \fB\-Z\fP option to \fBps\bP
.PP
Policy governs the access confined processes have to files.
SELinux cwalld policy is very flexible allowing users to setup their cwalld processes in as secure a method as possible.
.PP
The following process types are defined for cwalld:

.EX
.B cwalld_t
.EE
.PP
Note:
.B semanage permissive -a cwalld_t
can be used to make the process type cwalld_t permissive. SELinux does not deny access to permissive process types, but the AVC (SELinux denials) messages are still generated.

.SH BOOLEANS
SELinux policy is customizable based on least access required.  cwalld policy is extremely flexible and has several booleans that allow you to manipulate the policy and run cwalld with the tightest access possible.


.PP
If you want to dontaudit all daemons scheduling requests (setsched, sys_nice), you must turn on the daemons_dontaudit_scheduling boolean. Enabled by default.

.EX
.B setsebool -P daemons_dontaudit_scheduling 1

.EE

.PP
If you want to allow all domains to execute in fips_mode, you must turn on the fips_mode boolean. Enabled by default.

.EX
.B setsebool -P fips_mode 1

.EE

.SH "MANAGED FILES"

The SELinux process type cwalld_t can manage files labeled with the following file types.  The paths listed are the default paths for these file types.  Note the processes UID still need to have DAC permissions.

.br
.B cluster_conf_t

	/etc/cluster(/.*)?
.br

.br
.B cluster_var_lib_t

	/var/lib/pcsd(/.*)?
.br
	/var/lib/cluster(/.*)?
.br
	/var/lib/openais(/.*)?
.br
	/var/lib/pengine(/.*)?
.br
	/var/lib/corosync(/.*)?
.br
	/usr/lib/heartbeat(/.*)?
.br
	/var/lib/heartbeat(/.*)?
.br
	/var/lib/pacemaker(/.*)?
.br

.br
.B cluster_var_run_t

	/var/run/crm(/.*)?
.br
	/var/run/cman_.*
.br
	/var/run/rsctmp(/.*)?
.br
	/var/run/aisexec.*
.br
	/var/run/heartbeat(/.*)?
.br
	/var/run/pcsd-ruby.socket
.br
	/var/run/corosync-qnetd(/.*)?
.br
	/var/run/corosync-qdevice(/.*)?
.br
	/var/run/pcsd\.socket
.br
	/var/run/corosync\.pid
.br
	/var/run/cpglockd\.pid
.br
	/var/run/rgmanager\.pid
.br
	/var/run/cluster/rgmanager\.sk
.br

.br
.B root_t

	/sysroot/ostree/deploy/.*-atomic/deploy(/.*)?
.br
	/
.br
	/initrd
.br

.br
.B var_log_t

	/var/log/.*
.br
	/nsr/logs(/.*)?
.br
	/var/webmin(/.*)?
.br
	/var/log/secure[^/]*
.br
	/opt/zimbra/log(/.*)?
.br
	/var/log/maillog[^/]*
.br
	/var/log/spooler[^/]*
.br
	/var/log/messages[^/]*
.br
	/usr/centreon/log(/.*)?
.br
	/var/spool/rsyslog(/.*)?
.br
	/var/axfrdns/log/main(/.*)?
.br
	/var/spool/bacula/log(/.*)?
.br
	/var/tinydns/log/main(/.*)?
.br
	/var/dnscache/log/main(/.*)?
.br
	/var/stockmaniac/templates_cache(/.*)?
.br
	/opt/Symantec/scspagent/IDS/system(/.*)?
.br
	/var/log
.br
	/var/log/dmesg
.br
	/var/log/syslog
.br
	/var/named/chroot/var/log
.br

.SH "COMMANDS"
.B semanage fcontext
can also be used to manipulate default file context mappings.
.PP
.B semanage permissive
can also be used to manipulate whether or not a process type is permissive.
.PP
.B semanage module
can also be used to enable/disable/install/remove policy modules.

.B semanage boolean
can also be used to manipulate the booleans

.PP
.B system-config-selinux
is a GUI tool available to customize SELinux policy settings.

.SH AUTHOR
This manual page was auto-generated using
.B "sepolicy manpage".

.SH "SEE ALSO"
selinux(8), cwalld(8), semanage(8), restorecon(8), chcon(1), sepolicy(8), setsebool(8)